# Site settings
title: ArgenJam
description: This is the landing page for the ArgenJam Game Jam
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://tabrisarg.github.io/" # the base hostname & protocol for your site
email:
twitter_username:
github_username:

# Build settings
markdown: kramdown
